CREATE TABLE mytable(
   id       INTEGER  NOT NULL PRIMARY KEY 
  ,judul    VARCHAR(134) NOT NULL
  ,title    VARCHAR(29) NOT NULL
  ,artist   VARCHAR(39) NOT NULL
  ,folder   VARCHAR(112)
  ,album    VARCHAR(107)
  ,size     VARCHAR(8) NOT NULL
  ,duration VARCHAR(9) NOT NULL
  ,bitrate  VARCHAR(11) NOT NULL
  ,year     INTEGER  NOT NULL
  ,cover    VARCHAR(44) NOT NULL
  ,link     VARCHAR(95) NOT NULL
);
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14384,'Kenshi Yonezu - Flamingo.mp3','Flamingo','Kenshi Yonezu',NULL,'Flamingo/TEENAGE RIOT','7.49 MB','3:15 Mins','320000 Kbps',2018,'//osanime.wapkiz.com/cover/2854273/cover.jpg','https://osanime.wapkiz.com/filedownload/2854273/Flamingo-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14383,'Hello Sleepwalkers - Hyakkiyakou.mp3','Hyakkiyakou','Hello Sleepwalkers',NULL,'Liquid Soul and Solid Blood','9.49 MB','4:05 Mins','320000 Kbps',2020,'//osanime.wapkiz.com/cover/2854271/cover.jpg','https://osanime.wapkiz.com/filedownload/2854271/Hyakkiyakou-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14382,'Eve - Yuseiboushi.mp3','Yuseiboushi','Eve',NULL,'Yuseiboushi','7.49 MB','3:14 Mins','320039 Kbps',2021,'//osanime.wapkiz.com/cover/2854254/cover.jpg','https://osanime.wapkiz.com/filedownload/2854254/Yuseiboushi-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14381,'Yorushika - Matasaburo.mp3','Matasaburo','Yorushika',NULL,'Matasaburo','9.36 MB','3:48 Mins','320000 Kbps',2021,'//osanime.wapkiz.com/cover/2854193/cover.jpg','https://osanime.wapkiz.com/filedownload/2854193/Matasaburo-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14380,'yama - Haru wo Tsugeru.mp3','Haru wo Tsugeru','Yama',NULL,'Haru wo Tsugeru','7.7 MB','3:17 Mins','320000 Kbps',2020,'//osanime.wapkiz.com/cover/2854188/cover.jpg','https://osanime.wapkiz.com/filedownload/2854188/Haru-wo-Tsugeru-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14379,'No description','Isabella''s Lullaby','Takahiro Obata',NULL,'The Promised Neverland (Original Soundtrack) (Complete Edition)','5.8 MB','2:29 Mins','320055 Kbps',2019,'//osanime.wapkiz.com/cover/2854181/cover.jpg','https://osanime.wapkiz.com/filedownload/2854181/Isabella-apos-s-Lullaby-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14378,'Rokudenashi - Ai ga tomoru.mp3','Ai ga tomoru','Rokudenashi',NULL,'Ai ga tomoru','7.78 MB','3:19 Mins','320041 Kbps',2023,'//osanime.wapkiz.com/cover/2854173/cover.jpg','https://osanime.wapkiz.com/filedownload/2854173/Ai-ga-tomoru-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14377,'Ireisu - Brave [Opening Saikyou Tank no Meikyuu Kouryaku: Tairyoku 9999 no Rare Skill-mochi Tank, Yuusha Party wo Tsuihou sareru].mp3','Brave','Ireisu','Opening Saikyou Tank no Meikyuu Kouryaku: Tairyoku 9999 no Rare Skill-mochi Tank, Yuusha Party wo Tsuihou sareru','Saikyou Tank no Meikyuu Kouryaku: Tairyoku 9999 no Rare Skill-mochi Tank, Yuusha Party wo Tsuihou sareru OP','9.06 MB','3:49 Mins','320000 Kbps',2024,'//osanime.wapkiz.com/cover/2854162/cover.jpg','https://osanime.wapkiz.com/filedownload/2854162/Brave-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14376,'FZMZ feat. icy - Danger Danger [Opening 2 Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su].mp3','Danger Danger','FZMZ (feat','Opening 2 Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su','Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su OP2','10.2 MB','3:41 Mins','320034 Kbps',2024,'//osanime.wapkiz.com/cover/2854054/cover.jpg','https://osanime.wapkiz.com/filedownload/2854054/Danger-Danger-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14375,'AliA - Kokoro no Naka [Ending Kekkon Yubiwa Monogatari].mp3','Kokoro no Naka','AliA','Ending Kekkon Yubiwa Monogatari','Kekkon Yubiwa Monogatari ED','10.82 MB','4:02 Mins','320031 Kbps',2024,'//osanime.wapkiz.com/cover/2854052/cover.jpg','https://osanime.wapkiz.com/filedownload/2854052/Kokoro-no-Naka-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14374,'Sizuk - Lover''s Eye [Opening Kekkon Yubiwa Monogatari].mp3','Lovers Eye','Sizuk (feat','Opening Kekkon Yubiwa Monogatari','Kekkon Yubiwa Monogatari OP','12.02 MB','4:23 Mins','320029 Kbps',2024,'//osanime.wapkiz.com/cover/2854050/cover.jpg','https://osanime.wapkiz.com/filedownload/2854050/Lovers-Eye-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14373,'wacci - Ai wa Kusuri [Ending 2 Kusuriya no Hitorigoto].mp3','Ai wa Kusuri','Wacci','Ending 2 Kusuriya no Hitorigoto','Kusuriya no Hitorigoto ED2','10.44 MB','4:25 Mins','320029 Kbps',2024,'//osanime.wapkiz.com/cover/2854049/cover.jpg','https://osanime.wapkiz.com/filedownload/2854049/Ai-wa-Kusuri-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14372,'SawanoHiroyuki[nZk] - LEveL [Opening Ore dake Level Up na Ken].mp3','LEveL','SawanoHiroyuki[nZk]:TOMORROW X TOGETHER','Opening Ore dake Level Up na Ken','Ore dake Level Up na Ken OP','8.62 MB','3:00 Mins','320042 Kbps',2024,'//osanime.wapkiz.com/cover/2854037/cover.jpg','https://osanime.wapkiz.com/filedownload/2854037/LEveL-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14371,'Eve - Bokura Mada Underground.mp3','Bokura Mada Underground','Eve',NULL,'otogi','11.65 MB','5:02 Mins','320027 Kbps',2019,'//osanime.wapkiz.com/cover/2853952/cover.jpg','https://osanime.wapkiz.com/filedownload/2853952/Bokura-Mada-Underground-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14370,'Maaya Sakamoto - Mada Tooku ni Iru [Ending Hikari no Ou].mp3','Mada Tooku Ni Iru','Maaya Sakamoto','Ending Hikari no Ou','Mada Tooku Ni Iru','12.14 MB','5:15 Mins','320024 Kbps',2023,'//osanime.wapkiz.com/cover/2853941/cover.jpg','https://osanime.wapkiz.com/filedownload/2853941/Mada-Tooku-Ni-Iru-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14369,'Leo Ieiri - Usotsuki [Opening Hikari no Ou].mp3','Usotsuki','レオ','Opening Hikari no Ou',NULL,'8.36 MB','3:37 Mins','320035 Kbps',2023,'//osanime.wapkiz.com/cover/2853936/cover.jpg','https://osanime.wapkiz.com/filedownload/2853936/Usotsuki-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14368,'EGOIST - Sakase ya Sakase [Opening Koutetsujou no Kabaneri Movie 3: Unato Kessen].mp3','Sakase ya Sakase','EGOIST','Opening Koutetsujou no Kabaneri Movie 3: Unato Kessen','Sakase ya Sakase','8.23 MB','3:25 Mins','320000 Kbps',2019,'//osanime.wapkiz.com/cover/2853744/cover.jpg','https://osanime.wapkiz.com/filedownload/2853744/Sakase-ya-Sakase-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14367,'SawanoHiroyuki[nZk]:Aimer - ninelie  [Ending Koutetsujou no Kabaneri Movie 1: Tsudou Hikari].mp3','ninelie','SawanoHiroyuki[nZk]:Aimer','Ending Koutetsujou no Kabaneri Movie 1: Tsudou Hikari','ninelie','11.91 MB','5:05 Mins','320000 Kbps',2016,'//osanime.wapkiz.com/cover/2853734/cover.jpg','https://osanime.wapkiz.com/filedownload/2853734/ninelie-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14366,'Aimer x Chelly - Through My Blood  [Ending EP11 Koutetsujou no Kabaneri].mp3','Through My Blood','Aimer','Ending EP11 Koutetsujou no Kabaneri','ninelie','9.37 MB','4:04 Mins','320000 Kbps',2016,'//osanime.wapkiz.com/cover/2853732/cover.jpg','https://osanime.wapkiz.com/filedownload/2853732/Through-My-Blood-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14365,'Aimer x chelly - ninelie [Ending Koutetsujou no Kabaneri].mp3','ninelie','Aimer X Chelly','Ending Koutetsujou no Kabaneri','ninelie','10.03 MB','4:20 Mins','320000 Kbps',2016,'//osanime.wapkiz.com/cover/2853720/cover.jpg','https://osanime.wapkiz.com/filedownload/2853720/ninelie-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14364,'EGOIST - KABANERI OF THE IRON FORTRESS [Opening Koutetsujou no Kabaneri].mp3','KABANERI OF THE IRON FORTRESS','EGOIST','Opening Koutetsujou no Kabaneri','KABANERI OF THE IRON FORTRESS','11.34 MB','4:51 Mins','320000 Kbps',2016,'//osanime.wapkiz.com/cover/2853703/cover.jpg','https://osanime.wapkiz.com/filedownload/2853703/KABANERI-OF-THE-IRON-FORTRESS-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14363,'Muto - Aiko [Ending Momochi-san Chi no Ayakashi Ouji].mp3','Aiko','Muto','Ending Momochi-san Chi no Ayakashi Ouji','Momochi-san Chi no Ayakashi Ouji ED','10.37 MB','3:45 Mins','320034 Kbps',2024,'//osanime.wapkiz.com/cover/2853658/cover.jpg','https://osanime.wapkiz.com/filedownload/2853658/Aiko-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14362,'ChoQMay - snowspring [Ending Yubisaki to Renren].mp3','snowspring','ChoQMay','Ending Yubisaki to Renren','Yubisaki to Renren ED','8.94 MB','3:42 Mins','320000 Kbps',2024,'//osanime.wapkiz.com/cover/2853657/cover.jpg','https://osanime.wapkiz.com/filedownload/2853657/snowspring-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14361,'THIS IS JAPAN - new world [Ending NO GUNS LIFE 2nd Season].mp3','new world','THIS IS JAPAN','Ending NO GUNS LIFE 2nd Season','new world','7.57 MB','3:16 Mins','320000 Kbps',2020,'//osanime.wapkiz.com/cover/2853473/cover.jpg','https://osanime.wapkiz.com/filedownload/2853473/new-world-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14360,'SawanoHiroyuki[nZk]:Jean-Ken Johnny - Chaos Drifters [Opening NO GUNS LIFE 2nd Season].mp3','Chaos Drifters','SawanoHiroyuki[nZk]:Jean-Ken Johnny','Opening NO GUNS LIFE 2nd Season','Chaos Drifters','9.04 MB','3:49 Mins','320000 Kbps',2020,'//osanime.wapkiz.com/cover/2853468/cover.jpg','https://osanime.wapkiz.com/filedownload/2853468/Chaos-Drifters-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14359,'DATS - Game Over [Ending NO GUNS LIFE].mp3','Game Over','DATS','Ending NO GUNS LIFE','Game Over','9.03 MB','3:55 Mins','320035 Kbps',2019,'//osanime.wapkiz.com/cover/2853463/cover.jpg','https://osanime.wapkiz.com/filedownload/2853463/Game-Over-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14358,'Kenichi Asai - MOTOR CITY [Opening NO GUNS LIFE].mp3','MOTOR CITY','Kenichi Asai','Opening NO GUNS LIFE','MOTOR CITY','6.42 MB','2:48 Mins','320000 Kbps',2019,'//osanime.wapkiz.com/cover/2853320/cover.jpg','https://osanime.wapkiz.com/filedownload/2853320/MOTOR-CITY-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14357,'Nowlu - Rasen [Ending 2 Baraou no Souretsu].mp3','Rasen','Nowlu','Ending 2 Baraou no Souretsu','Rasen','10.7 MB','4:34 Mins','320000 Kbps',2022,'//osanime.wapkiz.com/cover/2853299/cover.jpg','https://osanime.wapkiz.com/filedownload/2853299/Rasen-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14356,'Makoto Furukawa - Ibara Rinbukyoku [Opening 2 Baraou no Souretsu].mp3','Ibara Rinbukyoku','Makoto Furukawa','Opening 2 Baraou no Souretsu','Ibara Rinbukyoku','10.17 MB','4:20 Mins','320000 Kbps',2022,'//osanime.wapkiz.com/cover/2853289/cover.jpg','https://osanime.wapkiz.com/filedownload/2853289/Ibara-Rinbukyoku-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14355,'ZAQ - Akumu [Ending Baraou no Souretsu].mp3','Akumu','ZAQ','Ending Baraou no Souretsu','Akumu','9.92 MB','4:15 Mins','320032 Kbps',2022,'//osanime.wapkiz.com/cover/2853263/cover.jpg','https://osanime.wapkiz.com/filedownload/2853263/Akumu-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14354,'Makoto Furukawa - Ware, Bara ni Insu [Opening Baraou no Souretsu].mp3','Ware, Bara ni Insu','Makoto Furukawa','Opening Baraou no Souretsu','Ware, Bara ni Insu','8.08 MB','3:28 Mins','320040 Kbps',2022,'//osanime.wapkiz.com/cover/2853260/cover.jpg','https://osanime.wapkiz.com/filedownload/2853260/Ware-Bara-ni-Insu-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14353,'Yorushika - Haru [Opening 2 Sousou no Frieren].mp3','Haru','Yorushika','Opening 2 Sousou no Frieren','Sousou no Frieren OP2','11.89 MB','4:31 Mins','320028 Kbps',2024,'//osanime.wapkiz.com/cover/2853217/cover.jpg','https://osanime.wapkiz.com/filedownload/2853217/Haru-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14352,'Hilcrhyme - Killer Bars [Opening Sokushi Cheat ga Saikyou sugite, Isekai no Yatsura ga Marude Aite ni Naranai n desu ga.].mp3','Killer Bars','Hilcrhyme','Opening Sokushi Cheat ga Saikyou sugite, Isekai no Yatsura ga Marude Aite ni Naranai n desu ga.','Sokushi Cheat ga Saikyou sugite, Isekai no Yatsura ga Marude Aite ni Naranai n desu ga','8.68 MB','3:23 Mins','320037 Kbps',2024,'//osanime.wapkiz.com/cover/2853212/cover.jpg','https://osanime.wapkiz.com/filedownload/2853212/Killer-Bars-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14351,'Maaya Uchida - CHA∞IN [Ending Mato Seihei no Slave].mp3','Chain','Maaya Uchida','Ending Mato Seihei no Slave','Mato Seihei no Slave ED','10.57 MB','4:05 Mins','320031 Kbps',2024,'//osanime.wapkiz.com/cover/2853208/cover.jpg','https://osanime.wapkiz.com/filedownload/2853208/Chain-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14350,'Akari Kitou - Yume no Ito [Opening Mato Seihei no Slave].mp3','Yume no Ito','Akari Kitou','Opening Mato Seihei no Slave','Mato Seihei no Slave OP','10.17 MB','3:31 Mins','320036 Kbps',2024,'//osanime.wapkiz.com/cover/2853199/cover.jpg','https://osanime.wapkiz.com/filedownload/2853199/Yume-no-Ito-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14349,'halca - Good Luck Waker [Ending Pon no Michi].mp3','Good Luck Waker','Halca','Ending Pon no Michi','Pon no Michi ED','9.17 MB','3:33 Mins','320036 Kbps',2024,'//osanime.wapkiz.com/cover/2853196/cover.jpg','https://osanime.wapkiz.com/filedownload/2853196/Good-Luck-Waker-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14348,'Kana Nakada feat. Pon no Michi All Stars - Pon Popopon [Opening Pon no Michi].mp3','Ponpopopon','Kana Nakada Feat','Opening Pon no Michi','Pon no Michi OP','8.93 MB','3:17 Mins','320039 Kbps',2024,'//osanime.wapkiz.com/cover/2853194/cover.jpg','https://osanime.wapkiz.com/filedownload/2853194/Ponpopopon-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14347,'MADKID - FLY [Opening Sasaki to Pii-chan].mp3','FLY','MADKID','Opening Sasaki to Pii-chan','Sasaki to Pii-chan OP','9.21 MB','3:32 Mins','320039 Kbps',2024,'//osanime.wapkiz.com/cover/2853193/cover.jpg','https://osanime.wapkiz.com/filedownload/2853193/FLY-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14346,'Hilcrhyme - Yoridokoro [Ending Peter Grill to Kenja no Jikan].mp3','Yoridokoro','Hilcrhyme','Ending Peter Grill to Kenja no Jikan','Yoridokoro','12.15 MB','4:28 Mins','320028 Kbps',2020,'//osanime.wapkiz.com/cover/2853103/cover.jpg','https://osanime.wapkiz.com/filedownload/2853103/Yoridokoro-(divakun.com).mp3');
INSERT INTO mytable(id,judul,title,artist,folder,album,size,duration,bitrate,year,cover,link) VALUES (14345,'Yui Ninomiya - Tsuranuite Yuuutsu [Opening Peter Grill to Kenja no Jikan].mp3','Tsuranuite Yuuutsu','Yui Ninomiya','Opening Peter Grill to Kenja no Jikan','Tsuranuite Yuuutsu','8.7 MB','3:45 Mins','320000 Kbps',2020,'//osanime.wapkiz.com/cover/2853091/cover.jpg','https://osanime.wapkiz.com/filedownload/2853091/Tsuranuite-Yuuutsu-(divakun.com).mp3');
